spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_manager
    username: user
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
